# Generated by Django 3.2.23 on 2024-01-20 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20240120_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='paid',
        ),
    ]
